// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDiwB_f2ACbYdXFtVF2WZWReXR76tMKZg',
    appId: '1:329647927446:web:6ccaae4555190e968652b7',
    messagingSenderId: '329647927446',
    projectId: 'hack-o-mania',
    authDomain: 'hack-o-mania.firebaseapp.com',
    storageBucket: 'hack-o-mania.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40dfDCtquN0JkoHWHvx4UMgqwKcZPNhk',
    appId: '1:329647927446:android:db514f52dc8962998652b7',
    messagingSenderId: '329647927446',
    projectId: 'hack-o-mania',
    storageBucket: 'hack-o-mania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBAXSGK8QnhK63x0AKDR27l8Phw7ZkV0',
    appId: '1:329647927446:ios:c8bd4e3900fe5cb28652b7',
    messagingSenderId: '329647927446',
    projectId: 'hack-o-mania',
    storageBucket: 'hack-o-mania.appspot.com',
    iosBundleId: 'com.example.hackOMania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBAXSGK8QnhK63x0AKDR27l8Phw7ZkV0',
    appId: '1:329647927446:ios:d3d8ed0169a58ff58652b7',
    messagingSenderId: '329647927446',
    projectId: 'hack-o-mania',
    storageBucket: 'hack-o-mania.appspot.com',
    iosBundleId: 'com.example.hackOMania.RunnerTests',
  );
}
